version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: tongducthanhnam/portfolio:latest
    ports:
      - "80:80"
    volumes:
      - ./config:/etc/httpd/conf
    command: /usr/sbin/httpd -D FOREGROUND

volumes:
  config: