/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JeanLescano (https://sketchfab.com/JeanLescano)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/window-7c34cb1c99544017a03119b566718399
Title: Window
*/

import * as THREE from 'three'
import React from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Material2: THREE.LineSegments
        Material2_1: THREE.Mesh
        Material2_2: THREE.Mesh
        Material2_3: THREE.Mesh
        Material2_4: THREE.Mesh
        Material2_5: THREE.Mesh
        Material2_6: THREE.Mesh
        Material2_7: THREE.Mesh
        Material2_8: THREE.LineSegments
        Material2_9: THREE.LineSegments
        Material2_10: THREE.LineSegments
        Material2_11: THREE.Mesh
        Material2_12: THREE.LineSegments
        Material2_13: THREE.LineSegments
        Material2_14: THREE.Mesh
        Material2_15: THREE.Mesh
        Material2_16: THREE.Mesh
        Material2_17: THREE.LineSegments
        Material2_18: THREE.LineSegments
        Material2_19: THREE.Mesh
        Material2_20: THREE.Mesh
        Material2_21: THREE.Mesh
        Material2_22: THREE.Mesh
        Material2_23: THREE.Mesh
        Material2_24: THREE.Mesh
        Material2_25: THREE.LineSegments
        Material2_26: THREE.LineSegments
        Material2_27: THREE.Mesh
        Material2_28: THREE.Mesh
        Material2_29: THREE.Mesh
        Material2_30: THREE.LineSegments
        Material2_31: THREE.LineSegments
        Material2_32: THREE.Mesh
        Material2_33: THREE.Mesh
        Material2_34: THREE.Mesh
        Material2_35: THREE.Mesh
        Material2_36: THREE.Mesh
        Material2_37: THREE.Mesh
        Material2_38: THREE.LineSegments
        Material2_39: THREE.LineSegments
        Material2_40: THREE.LineSegments
        Material2_41: THREE.LineSegments
        Material2_42: THREE.LineSegments
        Material2_43: THREE.LineSegments
        Material2_44: THREE.LineSegments
        Material2_45: THREE.LineSegments
        Material2_46: THREE.LineSegments
        Material2_47: THREE.LineSegments
        Material2_48: THREE.LineSegments
        Material2_49: THREE.LineSegments
        Material2_50: THREE.LineSegments
        Material2_51: THREE.Mesh
        Material2_52: THREE.LineSegments
        Material2_53: THREE.LineSegments
        Material2_54: THREE.Mesh
        Material2_55: THREE.Mesh
        Material2_56: THREE.Mesh
        Material2_57: THREE.Mesh
        Material2_58: THREE.Mesh
        Material2_59: THREE.Mesh
        Material2_60: THREE.LineSegments
        Material2_61: THREE.LineSegments
        Material2_62: THREE.LineSegments
        Material2_63: THREE.Mesh
        Material2_64: THREE.LineSegments
        Material2_65: THREE.LineSegments
        Material2_66: THREE.Mesh
        Material2_67: THREE.Mesh
        Material2_68: THREE.Mesh
        Material2_69: THREE.Mesh
        Material2_70: THREE.Mesh
        Material2_71: THREE.Mesh
        Material2_72: THREE.Mesh
        Material2_73: THREE.Mesh
        Material2_74: THREE.Mesh
        Material2_75: THREE.Mesh
        Material2_76: THREE.Mesh
        Material2_77: THREE.LineSegments
        Material2_78: THREE.LineSegments
        Material2_79: THREE.LineSegments
        Material2_80: THREE.Mesh
        Material2_81: THREE.LineSegments
        Material2_82: THREE.LineSegments
        Material2_83: THREE.Mesh
        Material2_84: THREE.Mesh
        Material2_85: THREE.LineSegments
        Material2_86: THREE.LineSegments
        Material2_87: THREE.Mesh
        Material2_88: THREE.Mesh
        Material2_89: THREE.Mesh
    }
    materials: {
        edge_color234234234255: THREE.LineBasicMaterial
        metal_blanco: THREE.MeshStandardMaterial
        Glass_Crystal: THREE.MeshStandardMaterial
        Generic: THREE.MeshStandardMaterial
        edge_color176176176255: THREE.LineBasicMaterial
        tornillos: THREE.MeshStandardMaterial
    },
}

export function Model(props: JSX.IntrinsicElements['group']) {
    const {nodes, materials} = useGLTF('/scene.gltf') as GLTFResult
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group
                    position={[-5.581, 23.0833, 14.5669]}
                    rotation={[0, 0, -2.618]}
                    scale={[1, 0.9993, 0.998]}>
                    <lineSegments
                        geometry={nodes.Material2.geometry}
                        material={materials.edge_color234234234255}
                    />
                    <group position={[0.9147, 23.235, 0.4399]} scale={[1.0321, 0.9831, 1.01]}>
                        <group position={[0.1093, 0, 0]}>
                            <mesh geometry={nodes.Material2_6.geometry} material={materials.metal_blanco}/>
                            <mesh geometry={nodes.Material2_7.geometry} material={materials.Glass_Crystal}/>
                            <lineSegments
                                geometry={nodes.Material2_8.geometry}
                                material={materials.edge_color234234234255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_9.geometry}
                                material={materials.edge_color234234234255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_10.geometry}
                                material={materials.edge_color234234234255}
                            />
                        </group>
                        <group position={[0.1093, 1.2138, 1.5748]}>
                            <group position={[0.3937, 10.0067, 28.7366]} scale={[1, 1, 0.9732]}>
                                <mesh geometry={nodes.Material2_11.geometry} material={materials.metal_blanco}/>
                                <lineSegments
                                    geometry={nodes.Material2_12.geometry}
                                    material={materials.edge_color234234234255}
                                />
                                <lineSegments
                                    geometry={nodes.Material2_13.geometry}
                                    material={materials.edge_color234234234255}
                                />
                            </group>
                            <group
                                position={[0.3937, 10.0076, 14.1767]}
                                rotation={[Math.PI, 0, -Math.PI]}
                                scale={[1, 1, 0.9732]}>
                                <mesh geometry={nodes.Material2_16.geometry} material={materials.metal_blanco}/>
                                <lineSegments
                                    geometry={nodes.Material2_17.geometry}
                                    material={materials.edge_color234234234255}
                                />
                                <lineSegments
                                    geometry={nodes.Material2_18.geometry}
                                    material={materials.edge_color234234234255}
                                />
                            </group>
                            <group
                                position={[0.3937, 11.1896, 28.7366]}
                                rotation={[0, 0, Math.PI]}
                                scale={[1, 1, 0.9732]}>
                                <mesh geometry={nodes.Material2_24.geometry} material={materials.metal_blanco}/>
                                <lineSegments
                                    geometry={nodes.Material2_25.geometry}
                                    material={materials.edge_color234234234255}
                                />
                                <lineSegments
                                    geometry={nodes.Material2_26.geometry}
                                    material={materials.edge_color234234234255}
                                />
                            </group>
                            <group
                                position={[0.3937, 11.1887, 14.1767]}
                                rotation={[-Math.PI, 0, 0]}
                                scale={[1, 1, 0.9732]}>
                                <mesh geometry={nodes.Material2_29.geometry} material={materials.metal_blanco}/>
                                <lineSegments
                                    geometry={nodes.Material2_30.geometry}
                                    material={materials.edge_color234234234255}
                                />
                                <lineSegments
                                    geometry={nodes.Material2_31.geometry}
                                    material={materials.edge_color234234234255}
                                />
                            </group>
                            <mesh
                                geometry={nodes.Material2_14.geometry}
                                material={materials.metal_blanco}
                                position={[0.3937, 21.1962, 13.5862]}
                                rotation={[0, 0, Math.PI]}
                                scale={[1, 1.01, 1]}
                            />
                            <mesh
                                geometry={nodes.Material2_15.geometry}
                                material={materials.metal_blanco}
                                position={[0.3937, 21.1809, 29.3272]}
                                rotation={[-Math.PI, 0, 0]}
                                scale={[1, 1.01, 1]}
                            />
                            <mesh
                                geometry={nodes.Material2_19.geometry}
                                material={materials.metal_blanco}
                                position={[0.3937, 0.0154, 14.7673]}
                                rotation={[Math.PI, 0, -Math.PI]}
                                scale={[1, 1.01, 1]}
                            />
                            <mesh
                                geometry={nodes.Material2_20.geometry}
                                material={materials.metal_blanco}
                                position={[0.3937, 0, 28.1461]}
                                scale={[1, 1.01, 1]}
                            />
                            <mesh
                                geometry={nodes.Material2_21.geometry}
                                material={materials.metal_blanco}
                                position={[0.3937, 10.0076, 28.7366]}
                                rotation={[Math.PI, 0, -Math.PI]}
                                scale={[1, 1, 0.9732]}
                            />
                            <mesh
                                geometry={nodes.Material2_22.geometry}
                                material={materials.metal_blanco}
                                position={[0.3937, 0.0154, 29.3272]}
                                rotation={[Math.PI, 0, -Math.PI]}
                                scale={[1, 1.01, 1]}
                            />
                            <mesh
                                geometry={nodes.Material2_23.geometry}
                                material={materials.metal_blanco}
                                position={[0.3937, 21.1809, 14.7673]}
                                rotation={[-Math.PI, 0, 0]}
                                scale={[1, 1.01, 1]}
                            />
                            <mesh
                                geometry={nodes.Material2_27.geometry}
                                material={materials.metal_blanco}
                                position={[0.3937, 21.1962, 28.1461]}
                                rotation={[0, 0, Math.PI]}
                                scale={[1, 1.01, 1]}
                            />
                            <mesh
                                geometry={nodes.Material2_28.geometry}
                                material={materials.metal_blanco}
                                position={[0.3937, 0, 13.5862]}
                                scale={[1, 1.01, 1]}
                            />
                            <mesh
                                geometry={nodes.Material2_32.geometry}
                                material={materials.metal_blanco}
                                position={[0.3937, 11.1887, 28.7366]}
                                rotation={[-Math.PI, 0, 0]}
                                scale={[1, 1, 0.9732]}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Material2_5.geometry}
                            material={materials.metal_blanco}
                            position={[0, 0.8384, 11.6942]}
                        />
                    </group>
                    <group position={[0.2346, 0.7874, 0.4399]}>
                        <group position={[0.0492, 23.5656, 10.7182]} scale={[1, 0.9831, 1.01]}>
                            <mesh geometry={nodes.Material2_33.geometry} material={materials.Generic}/>
                            <mesh geometry={nodes.Material2_34.geometry} material={materials.Generic}/>
                            <mesh geometry={nodes.Material2_35.geometry} material={materials.Generic}/>
                            <mesh geometry={nodes.Material2_36.geometry} material={materials.Generic}/>
                            <mesh geometry={nodes.Material2_37.geometry} material={materials.Generic}/>
                            <mesh geometry={nodes.Material2_38.geometry} material={materials.Generic}/>
                            <lineSegments
                                geometry={nodes.Material2_39.geometry}
                                material={materials.edge_color176176176255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_40.geometry}
                                material={materials.edge_color176176176255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_41.geometry}
                                material={materials.edge_color176176176255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_42.geometry}
                                material={materials.edge_color176176176255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_43.geometry}
                                material={materials.edge_color176176176255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_44.geometry}
                                material={materials.edge_color176176176255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_45.geometry}
                                material={materials.edge_color176176176255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_46.geometry}
                                material={materials.edge_color176176176255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_47.geometry}
                                material={materials.edge_color176176176255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_48.geometry}
                                material={materials.edge_color176176176255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_49.geometry}
                                material={materials.edge_color176176176255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_50.geometry}
                                material={materials.edge_color176176176255}
                            />
                        </group>
                        <group
                            position={[0.3937, 12.1905, 15.9091]}
                            rotation={[-Math.PI, 0, 0]}
                            scale={[1, 0.9831, 0.9829]}>
                            <mesh geometry={nodes.Material2_51.geometry} material={materials.metal_blanco}/>
                            <lineSegments
                                geometry={nodes.Material2_52.geometry}
                                material={materials.edge_color234234234255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_53.geometry}
                                material={materials.edge_color234234234255}
                            />
                        </group>
                        <group scale={[1, 0.9831, 1.01]}>
                            <mesh geometry={nodes.Material2_58.geometry} material={materials.metal_blanco}/>
                            <mesh geometry={nodes.Material2_59.geometry} material={materials.Glass_Crystal}/>
                            <lineSegments
                                geometry={nodes.Material2_60.geometry}
                                material={materials.edge_color234234234255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_61.geometry}
                                material={materials.edge_color234234234255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_62.geometry}
                                material={materials.edge_color234234234255}
                            />
                        </group>
                        <group
                            position={[0.3937, 11.0294, 15.9091]}
                            rotation={[Math.PI, 0, Math.PI]}
                            scale={[1, 0.9831, 0.9829]}>
                            <mesh geometry={nodes.Material2_63.geometry} material={materials.metal_blanco}/>
                            <lineSegments
                                geometry={nodes.Material2_64.geometry}
                                material={materials.edge_color234234234255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_65.geometry}
                                material={materials.edge_color234234234255}
                            />
                        </group>
                        <group position={[0, 22.9314, 11.1282]} scale={[1, 0.9831, 1.01]}>
                            <mesh geometry={nodes.Material2_68.geometry} material={materials.Generic}/>
                            <mesh geometry={nodes.Material2_69.geometry} material={materials.Generic}/>
                            <mesh geometry={nodes.Material2_70.geometry} material={materials.Generic}/>
                            <mesh geometry={nodes.Material2_71.geometry} material={materials.tornillos}/>
                            <mesh geometry={nodes.Material2_72.geometry} material={materials.tornillos}/>
                            <mesh geometry={nodes.Material2_73.geometry} material={materials.Generic}/>
                            <mesh geometry={nodes.Material2_74.geometry} material={materials.Generic}/>
                            <mesh geometry={nodes.Material2_75.geometry} material={materials.Generic}/>
                            <mesh geometry={nodes.Material2_76.geometry} material={materials.Generic}/>
                            <lineSegments
                                geometry={nodes.Material2_77.geometry}
                                material={materials.edge_color176176176255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_78.geometry}
                                material={materials.edge_color176176176255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_79.geometry}
                                material={materials.edge_color176176176255}
                            />
                        </group>
                        <group position={[0.3937, 11.0285, 30.6146]} scale={[1, 0.9831, 0.9829]}>
                            <mesh geometry={nodes.Material2_80.geometry} material={materials.metal_blanco}/>
                            <lineSegments
                                geometry={nodes.Material2_81.geometry}
                                material={materials.edge_color234234234255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_82.geometry}
                                material={materials.edge_color234234234255}
                            />
                        </group>
                        <group
                            position={[0.3937, 12.1914, 30.6146]}
                            rotation={[0, 0, -Math.PI]}
                            scale={[1, 0.9831, 0.9829]}>
                            <mesh geometry={nodes.Material2_84.geometry} material={materials.metal_blanco}/>
                            <lineSegments
                                geometry={nodes.Material2_85.geometry}
                                material={materials.edge_color234234234255}
                            />
                            <lineSegments
                                geometry={nodes.Material2_86.geometry}
                                material={materials.edge_color234234234255}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Material2_54.geometry}
                            material={materials.metal_blanco}
                            position={[0.3937, 1.2066, 31.211]}
                            rotation={[Math.PI, 0, -Math.PI]}
                            scale={[1, 0.9929, 1.01]}
                        />
                        <mesh
                            geometry={nodes.Material2_55.geometry}
                            material={materials.metal_blanco}
                            position={[0.3937, 22.0133, 31.211]}
                            rotation={[-Math.PI, 0, 0]}
                            scale={[1, 0.9929, 1.01]}
                        />
                        <mesh
                            geometry={nodes.Material2_56.geometry}
                            material={materials.metal_blanco}
                            position={[0.3937, 22.0284, 15.3126]}
                            rotation={[0, 0, -Math.PI]}
                            scale={[1, 0.9929, 1.01]}
                        />
                        <mesh
                            geometry={nodes.Material2_57.geometry}
                            material={materials.metal_blanco}
                            position={[0.3937, 11.0294, 30.6146]}
                            rotation={[Math.PI, 0, Math.PI]}
                            scale={[1, 0.9831, 0.9829]}
                        />
                        <mesh
                            geometry={nodes.Material2_66.geometry}
                            material={materials.metal_blanco}
                            position={[0.3937, 12.1905, 30.6146]}
                            rotation={[-Math.PI, 0, 0]}
                            scale={[1, 0.9831, 0.9829]}
                        />
                        <mesh
                            geometry={nodes.Material2_67.geometry}
                            material={materials.metal_blanco}
                            position={[0.3937, 22.0284, 30.0181]}
                            rotation={[0, 0, -Math.PI]}
                            scale={[1, 0.9929, 1.01]}
                        />
                        <mesh
                            geometry={nodes.Material2_83.geometry}
                            material={materials.metal_blanco}
                            position={[0.3937, 1.1914, 30.0181]}
                            scale={[1, 0.9929, 1.01]}
                        />
                        <mesh
                            geometry={nodes.Material2_87.geometry}
                            material={materials.metal_blanco}
                            position={[0.3937, 1.1914, 15.3126]}
                            scale={[1, 0.9929, 1.01]}
                        />
                        <mesh
                            geometry={nodes.Material2_88.geometry}
                            material={materials.metal_blanco}
                            position={[0.3937, 1.2066, 16.5055]}
                            rotation={[Math.PI, 0, -Math.PI]}
                            scale={[1, 0.9929, 1.01]}
                        />
                        <mesh
                            geometry={nodes.Material2_89.geometry}
                            material={materials.metal_blanco}
                            position={[0.3937, 22.0133, 16.5055]}
                            rotation={[-Math.PI, 0, 0]}
                            scale={[1, 0.9929, 1.01]}
                        />
                    </group>
                    <mesh
                        geometry={nodes.Material2_1.geometry}
                        material={materials.metal_blanco}
                        position={[0, 47.2441, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                        geometry={nodes.Material2_2.geometry}
                        material={materials.metal_blanco}
                        position={[2.0655, 47.2441, 47.3365]}
                        rotation={[Math.PI / 2, 0, -Math.PI]}
                    />
                    <mesh
                        geometry={nodes.Material2_3.geometry}
                        material={materials.metal_blanco}
                        position={[0.0323, 0, 0.0462]}
                    />
                    <mesh
                        geometry={nodes.Material2_4.geometry}
                        material={materials.metal_blanco}
                        position={[0.0323, 46.3452, 0.0462]}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/scene.gltf')
